ref: replace extensions with flext
app-anvil/waste_not pull request #28
Opened 2023-11-25 11:48 UTC by gianmarcocalbi

Closes #26

2023-11-25 14:56 UTC, mrcsilverfox requested changes

2023-11-25 14:56 UTC, mrcsilverfox commented on packages/aev_sdk/lib/src/widgets/input/selection_input.dart
> -import 'package:app/styles/styles.dart';
probabilmente non la useremo mai, perché utilizzeremo il modal bottom sheet

2023-12-04 08:43 UTC, gianmarcocalbi commented on app/lib/styles/app_colors.dart
> +  @Deprecated('Colors should be accessed via context theme')
facciamolo tramite seed

2023-12-04 08:52 UTC, gianmarcocalbi commented on app/lib/styles/app_colors.dart
> +@Deprecated('Colors should be accessed via context theme')
il colore di errore è già nel tema, gli altri ok

2023-12-08 13:03 UTC, mrcsilverfox commented on app/lib/styles/app_colors.dart
> +  @Deprecated('Colors should be accessed via context theme')
no dai sono 2 colori

2023-12-08 23:25 UTC, merged