feat: implement flow to add item by scanning
app-anvil/waste_not pull request #29
Opened 2023-11-26 14:53 UTC by mrcsilverfox

2023-12-05 15:21 UTC, gianmarcocalbi requested changes

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/add_item_page.dart
> +        // FIXME: [text]
```suggestion
        // FIXME: l10n
```

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/add_item_page.dart
> +                      // TODO(calbi): add shimmer
?

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/add_item_page.dart
> +                    hintText: 'Expiration date',
l10n

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/add_item_page.dart
> +                        value == null ? 'Required field' : null,
l10n

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/add_item_page.dart
> +                    hintText: 'Select a storage',
l10n

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/add_item_page.dart
> +                        value == null ? 'Required field' : null,
ricontrolla tutti l10n nel file che sono mille

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/add_item_page.dart
> +}
O_O

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/inventory/view/inventory_page.dart
> +        ),
fallo non lazy

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/items/cubit/items_cubit.dart
> +      emit(state.copyWithError(e.toString()));
pure qua

2023-12-05 15:21 UTC, gianmarcocalbi commented on app/lib/features/items/items.dart
> +
utile

2023-12-07 08:14 UTC, mrcsilverfox commented on app/lib/db/isar_service.dart
> +// TODO(calbi): define the interface inside the common package. In this way, the class
Bravo

2023-12-07 08:15 UTC, mrcsilverfox commented on app/lib/features/add_item/cubit/add_item_cubit.dart
> +      emit(state.copyWithError(e.toString()));
Per ora poi le gestiremo

2023-12-07 08:16 UTC, mrcsilverfox commented on app/lib/features/inventory/view/inventory_page.dart
> +        ),
No non cambia per come gestiamo le cose

2023-12-09 10:41 UTC, merged