feat: Add open food facts products api repository
app-anvil/waste_not pull request #3
Opened 2023-10-29 00:18 UTC by mrcsilverfox

Closes #2

2023-10-29 00:18 UTC, mrcsilverfox commented
Mancano i log e gestire le diverse tipologie di errori ritornati dall''api di open food facts

2023-10-30 20:38 UTC, gianmarcocalbi requested changes

2023-10-30 20:38 UTC, gianmarcocalbi commented on packages/base_products_repository/lib/src/domain/entities/base_product_entity.dart
> +class BaseProductEntity {
interface?

2023-10-30 22:10 UTC, mrcsilverfox commented on packages/base_products_repository/lib/src/data/models/base_product_model.dart
> +class BaseProductModel extends BaseProductEntity {
Si sì dividiamo

2023-11-01 18:53 UTC, mrcsilverfox commented on packages/base_products_repository/lib/src/domain/entities/base_product_entity.dart
> +class BaseProductEntity {
interfaccia no, abstract e la estendiamo direi

2023-11-02 18:09 UTC, merged