ref: improve fetch product error
app-anvil/waste_not pull request #53
Opened 2024-03-20 20:26 UTC by mrcsilverfox

Closes #45

2024-03-28 15:26 UTC, gianmarcocalbi requested changes

2024-03-28 15:26 UTC, gianmarcocalbi commented on app/lib/utils/app_haptics.dart
roba da mettere nell'SDK eh

2024-03-30 12:11 UTC, mrcsilverfox commented on app/lib/utils/app_haptics.dart
Ok metto un Todo per te

2024-04-01 09:53 UTC, gianmarcocalbi approved these changes

2024-04-01 09:53 UTC, merged