ref: add item
app-anvil/waste_not pull request #69
Opened 2024-04-25 18:02 UTC by mrcsilverfox

2024-04-29 16:08 UTC, gianmarcocalbi requested changes

2024-04-29 16:08 UTC, gianmarcocalbi commented on app/lib/features/add_item/cubit/add_item_state.dart
> +    return expirationDate != null && storage != null;
chiama il validatore di `amount`

2024-04-29 16:08 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/widgets/add_edit_item_form.dart
> +            labelText: 'Units',
```suggestion
            labelText: 'Amount',
```

2024-04-29 16:08 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/widgets/add_edit_item_form.dart
> +            hintText: 'Enter a units of product you buyed',
```suggestion
            hintText: 'Enter how many items you want to add',
```

2024-04-29 16:08 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/widgets/add_edit_item_form.dart
> +          inputFormatters: [ReplaceCommaFormatter('.')],
a che serve qui?

2024-04-29 16:08 UTC, gianmarcocalbi commented on app/lib/features/add_item/view/widgets/add_edit_item_form.dart
> +        return TextFormField(
cosa succede se l'utente inserisce `0`?

2024-04-29 18:28 UTC, mrcsilverfox commented on app/lib/features/add_item/view/widgets/add_edit_item_form.dart
> +          validator: (_) => amount.error?.message,
`amount.error` richiama il validator e ritorna eventalmente il messaggio di errore.
amount è già aggiornato quindi non serve il paramentro `v`.

2024-04-30 17:40 UTC, gianmarcocalbi approved these changes

2024-04-30 17:40 UTC, merged